import type { TicketStatus } from '@/components/ui/status-badge'
import type { Priority } from '@/components/ui/priority-badge'
import type { SlaState } from '@/components/ui/sla-timer'
import type { TierLevel } from '@/components/ui/tier-badge'

export interface Ticket {
  id: string
  subject: string
  category: string
  priority: Priority
  status: TicketStatus
  requester: string
  requesterInitials: string
  tenant: string
  tenantColor: string
  assignee?: string
  assigneeInitials?: string
  currentTier: TierLevel
  firstResponseSla: { display: string; state: SlaState; progress: number }
  resolutionSla: { display: string; state: SlaState; progress: number }
  lastActivity: string
  created: string
  channel: 'portal' | 'email'
  shipmentRef?: string
  tags?: string[]
  isPortalPartner?: boolean
}

export const mockTickets: Ticket[] = [
  {
    id: 'TKT-10428',
    subject: 'Container MRSU2381746 not showing latest status',
    category: 'Shipment/Tracking',
    priority: 'p2',
    status: 'open',
    requester: 'Priya Nair',
    requesterInitials: 'PN',
    tenant: 'Meridian Freight',
    tenantColor: '#2563EB',
    assignee: 'Arjun Mehta',
    assigneeInitials: 'AM',
    currentTier: 2,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: '3h 22m', state: 'at-risk', progress: 78 },
    lastActivity: '14 min ago',
    created: '2025-07-21T09:00:00Z',
    channel: 'portal',
    shipmentRef: 'MRSU2381746',
  },
  {
    id: 'TKT-10431',
    subject: 'Duplicate invoice on August billing run',
    category: 'Billing',
    priority: 'p2',
    status: 'escalated',
    requester: 'Rohan Das',
    requesterInitials: 'RD',
    tenant: 'Meridian Freight',
    tenantColor: '#2563EB',
    assignee: 'Sneha Pillai',
    assigneeInitials: 'SP',
    currentTier: 3,
    firstResponseSla: { display: 'OVERDUE 1h 12m', state: 'breached', progress: 100 },
    resolutionSla: { display: 'OVERDUE 22m', state: 'breached', progress: 100 },
    lastActivity: '2h ago',
    created: '2025-07-21T06:00:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10435',
    subject: 'Bulk upload CSV rejects valid HS codes',
    category: 'Technical',
    priority: 'p3',
    status: 'pending_requester',
    requester: 'Meera Iyer',
    requesterInitials: 'MI',
    tenant: 'Hanseatic Logistics',
    tenantColor: '#16A34A',
    assignee: 'Arjun Mehta',
    assigneeInitials: 'AM',
    currentTier: 1,
    firstResponseSla: { display: 'Paused', state: 'paused', progress: 0 },
    resolutionSla: { display: 'Paused', state: 'paused', progress: 0 },
    lastActivity: '1h ago',
    created: '2025-07-20T14:00:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10437',
    subject: 'Reefer container temperature log not accessible',
    category: 'Technical',
    priority: 'p1',
    status: 'new',
    requester: 'Kabir Singh',
    requesterInitials: 'KS',
    tenant: 'Apex Cold Chain',
    tenantColor: '#7C3AED',
    currentTier: 1,
    firstResponseSla: { display: '12m', state: 'at-risk', progress: 88 },
    resolutionSla: { display: '1h 48m', state: 'on-track', progress: 25 },
    lastActivity: 'Just now',
    created: '2025-07-22T08:50:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10440',
    subject: 'Security: unauthorized API access attempt detected',
    category: 'Security',
    priority: 'p1',
    status: 'escalated',
    requester: 'Tomás Bauer',
    requesterInitials: 'TB',
    tenant: 'Hanseatic Logistics',
    tenantColor: '#16A34A',
    assignee: 'Falcon (Vikram Rao)',
    assigneeInitials: 'VR',
    currentTier: 4,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: '1h 05m', state: 'at-risk', progress: 82 },
    lastActivity: '5 min ago',
    created: '2025-07-22T07:00:00Z',
    channel: 'portal',
    isPortalPartner: false,
  },
  {
    id: 'TKT-10441',
    subject: 'EDI partner not receiving dispatch notifications',
    category: 'Technical',
    priority: 'p2',
    status: 'open',
    requester: 'Lars Eriksson',
    requesterInitials: 'LE',
    tenant: 'Meridian Freight',
    tenantColor: '#2563EB',
    assignee: 'Sneha Pillai',
    assigneeInitials: 'SP',
    currentTier: 2,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: '6h 10m', state: 'on-track', progress: 45 },
    lastActivity: '30 min ago',
    created: '2025-07-22T06:30:00Z',
    channel: 'email',
    isPortalPartner: true,
  },
  {
    id: 'TKT-10443',
    subject: 'How to configure automatic customs clearance alerts?',
    category: 'How-to',
    priority: 'p4',
    status: 'resolved',
    requester: 'Ana Lima',
    requesterInitials: 'AL',
    tenant: 'Apex Cold Chain',
    tenantColor: '#7C3AED',
    assignee: 'Arjun Mehta',
    assigneeInitials: 'AM',
    currentTier: 1,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: 'Met', state: 'met', progress: 100 },
    lastActivity: 'Yesterday',
    created: '2025-07-21T11:00:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10445',
    subject: 'Freight cost calculation incorrect for multi-leg shipments',
    category: 'Billing',
    priority: 'p3',
    status: 'open',
    requester: 'Divya Kumar',
    requesterInitials: 'DK',
    tenant: 'SilkRoute Express',
    tenantColor: '#D97706',
    assignee: undefined,
    currentTier: 1,
    firstResponseSla: { display: '4h 30m', state: 'on-track', progress: 30 },
    resolutionSla: { display: '2d 3h', state: 'on-track', progress: 12 },
    lastActivity: '1h ago',
    created: '2025-07-22T07:00:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10447',
    subject: 'Port congestion alert feed missing for JNPT',
    category: 'Technical',
    priority: 'p2',
    status: 'new',
    requester: 'Marcus Webb',
    requesterInitials: 'MW',
    tenant: 'BlueSky Freight',
    tenantColor: '#0891B2',
    currentTier: 1,
    firstResponseSla: { display: '1h 45m', state: 'on-track', progress: 55 },
    resolutionSla: { display: '7h 15m', state: 'on-track', progress: 20 },
    lastActivity: '2h ago',
    created: '2025-07-22T05:30:00Z',
    channel: 'email',
  },
  {
    id: 'TKT-10450',
    subject: 'Vehicle tracking GPS offline for fleet GJ-14 batch',
    category: 'Technical',
    priority: 'p1',
    status: 'open',
    requester: 'Nitesh Sharma',
    requesterInitials: 'NS',
    tenant: 'SilkRoute Express',
    tenantColor: '#D97706',
    assignee: 'Sneha Pillai',
    assigneeInitials: 'SP',
    currentTier: 2,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: '47m', state: 'at-risk', progress: 91 },
    lastActivity: '8 min ago',
    created: '2025-07-22T08:00:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10452',
    subject: 'Invoice PDF generation fails for combined B/L',
    category: 'Billing',
    priority: 'p3',
    status: 'pending_requester',
    requester: 'Helen Park',
    requesterInitials: 'HP',
    tenant: 'BlueSky Freight',
    tenantColor: '#0891B2',
    assignee: 'Arjun Mehta',
    assigneeInitials: 'AM',
    currentTier: 1,
    firstResponseSla: { display: 'Paused', state: 'paused', progress: 0 },
    resolutionSla: { display: 'Paused', state: 'paused', progress: 0 },
    lastActivity: '3h ago',
    created: '2025-07-21T15:00:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10419',
    subject: 'Customs declaration stuck in pending validation',
    category: 'Shipment/Tracking',
    priority: 'p2',
    status: 'open',
    requester: 'Yuki Tanaka',
    requesterInitials: 'YT',
    tenant: 'Hanseatic Logistics',
    tenantColor: '#16A34A',
    currentTier: 1,
    firstResponseSla: { display: '2h 10m', state: 'on-track', progress: 42 },
    resolutionSla: { display: '1d 4h', state: 'on-track', progress: 18 },
    lastActivity: '45 min ago',
    created: '2025-07-22T06:00:00Z',
    channel: 'email',
    shipmentRef: 'HLCU9920144',
  },
  {
    id: 'TKT-10420',
    subject: 'User role permissions not syncing after org restructure',
    category: 'Technical',
    priority: 'p3',
    status: 'closed',
    requester: 'Fatima Al-Rashid',
    requesterInitials: 'FA',
    tenant: 'SilkRoute Express',
    tenantColor: '#D97706',
    assignee: 'Devika Rao',
    assigneeInitials: 'DR',
    currentTier: 2,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: 'Met', state: 'met', progress: 100 },
    lastActivity: 'Yesterday',
    created: '2025-07-19T10:00:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10453',
    subject: 'AWB number mismatch on Hamburg–Mumbai lane booking',
    category: 'Shipment/Tracking',
    priority: 'p2',
    status: 'new',
    requester: 'Ingrid Hoffmann',
    requesterInitials: 'IH',
    tenant: 'Hanseatic Logistics',
    tenantColor: '#16A34A',
    currentTier: 1,
    firstResponseSla: { display: '38m', state: 'at-risk', progress: 72 },
    resolutionSla: { display: '5h 20m', state: 'on-track', progress: 35 },
    lastActivity: '12 min ago',
    created: '2025-07-22T09:10:00Z',
    channel: 'portal',
    shipmentRef: 'AWB-489201773',
  },
  {
    id: 'TKT-10454',
    subject: 'Cold chain compliance report export timing out',
    category: 'Compliance',
    priority: 'p3',
    status: 'open',
    requester: 'Vikram Desai',
    requesterInitials: 'VD',
    tenant: 'Apex Cold Chain',
    tenantColor: '#7C3AED',
    assignee: 'Kiran Bose',
    assigneeInitials: 'KB',
    currentTier: 1,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: '4h 55m', state: 'on-track', progress: 52 },
    lastActivity: '22 min ago',
    created: '2025-07-22T07:45:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10456',
    subject: 'Rate card not applying promotional discount for GCC routes',
    category: 'Billing',
    priority: 'p2',
    status: 'open',
    requester: 'Omar Hassan',
    requesterInitials: 'OH',
    tenant: 'SilkRoute Express',
    tenantColor: '#D97706',
    currentTier: 1,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: 'OVERDUE 35m', state: 'breached', progress: 100 },
    lastActivity: '18 min ago',
    created: '2025-07-22T06:15:00Z',
    channel: 'email',
  },
  {
    id: 'TKT-10457',
    subject: 'Need API documentation for webhook retry configuration',
    category: 'How-to',
    priority: 'p4',
    status: 'pending_requester',
    requester: 'Chloe Nguyen',
    requesterInitials: 'CN',
    tenant: 'BlueSky Freight',
    tenantColor: '#0891B2',
    assignee: 'Arjun Mehta',
    assigneeInitials: 'AM',
    currentTier: 1,
    firstResponseSla: { display: 'Paused', state: 'paused', progress: 0 },
    resolutionSla: { display: 'Paused', state: 'paused', progress: 0 },
    lastActivity: '4h ago',
    created: '2025-07-21T12:00:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10458',
    subject: 'Credit note not reflected in July statement',
    category: 'Billing',
    priority: 'p2',
    status: 'escalated',
    requester: 'Elena Popescu',
    requesterInitials: 'EP',
    tenant: 'Apex Cold Chain',
    tenantColor: '#7C3AED',
    assignee: 'Sneha Pillai',
    assigneeInitials: 'SP',
    currentTier: 3,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: '2h 40m', state: 'at-risk', progress: 74 },
    lastActivity: '35 min ago',
    created: '2025-07-21T16:30:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10459',
    subject: 'Dashboard widget showing stale vessel ETA data',
    category: 'Technical',
    priority: 'p3',
    status: 'resolved',
    requester: 'Jonas Berg',
    requesterInitials: 'JB',
    tenant: 'Hanseatic Logistics',
    tenantColor: '#16A34A',
    assignee: 'Devika Rao',
    assigneeInitials: 'DR',
    currentTier: 1,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: 'Met', state: 'met', progress: 100 },
    lastActivity: 'Yesterday',
    created: '2025-07-20T08:00:00Z',
    channel: 'portal',
  },
  {
    id: 'TKT-10462',
    subject: 'Two-factor authentication reset for branch admin account',
    category: 'Security',
    priority: 'p1',
    status: 'new',
    requester: 'Amir Khan',
    requesterInitials: 'AK',
    tenant: 'Meridian Freight',
    tenantColor: '#2563EB',
    currentTier: 1,
    firstResponseSla: { display: '22m', state: 'at-risk', progress: 85 },
    resolutionSla: { display: '3h 10m', state: 'on-track', progress: 28 },
    lastActivity: '6 min ago',
    created: '2025-07-22T09:25:00Z',
    channel: 'email',
  },
  {
    id: 'TKT-10463',
    subject: 'Awaiting POD upload for Chennai gate-out confirmation',
    category: 'Shipment/Tracking',
    priority: 'p3',
    status: 'pending_requester',
    requester: 'Ananya Reddy',
    requesterInitials: 'AR',
    tenant: 'Meridian Freight',
    tenantColor: '#2563EB',
    assignee: 'Arjun Mehta',
    assigneeInitials: 'AM',
    currentTier: 1,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: 'Paused', state: 'paused', progress: 0 },
    lastActivity: '2h ago',
    created: '2025-07-21T11:00:00Z',
    channel: 'portal',
    shipmentRef: 'MSKU4412098',
  },
  {
    id: 'TKT-10464',
    subject: 'Customer clarification needed on reefer set-point change',
    category: 'Technical',
    priority: 'p2',
    status: 'pending_requester',
    requester: 'Deepak Menon',
    requesterInitials: 'DM',
    tenant: 'Apex Cold Chain',
    tenantColor: '#7C3AED',
    assignee: 'Kiran Bose',
    assigneeInitials: 'KB',
    currentTier: 2,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: 'Paused', state: 'paused', progress: 0 },
    lastActivity: '5h ago',
    created: '2025-07-20T16:00:00Z',
    channel: 'email',
  },
  {
    id: 'TKT-10465',
    subject: 'Missing signed LOI for hazardous cargo declaration',
    category: 'Compliance',
    priority: 'p2',
    status: 'pending_requester',
    requester: 'Rohan Das',
    requesterInitials: 'RD',
    tenant: 'Meridian Freight',
    tenantColor: '#2563EB',
    assignee: 'Sneha Pillai',
    assigneeInitials: 'SP',
    currentTier: 2,
    firstResponseSla: { display: 'Met', state: 'met', progress: 100 },
    resolutionSla: { display: 'Paused', state: 'paused', progress: 0 },
    lastActivity: '1d ago',
    created: '2025-07-19T09:30:00Z',
    channel: 'portal',
  },
]

export const mockEscalationHistory = [
  {
    id: 'esc-001',
    fromTier: 1 as TierLevel,
    toTier: 2 as TierLevel,
    trigger: 'SLA Breach',
    actor: 'System (Auto)',
    reason: 'First-response SLA breached (P2 Technical · 4h window)',
    timestamp: '2025-07-22T07:45:00Z',
  },
  {
    id: 'esc-002',
    fromTier: 2 as TierLevel,
    toTier: 3 as TierLevel,
    trigger: 'Manual',
    actor: 'Arjun Mehta',
    reason: 'Billing discrepancy requires Company-level finance approval. Invoice totals $42,000 over two months.',
    timestamp: '2025-07-22T09:15:00Z',
  },
]

export const mockNotifications = [
  { id: 'n1', type: 'breach', title: 'TKT-10431 breached first-response SLA', ticket: 'TKT-10431', time: '2h ago', read: false },
  { id: 'n2', type: 'escalation', title: 'TKT-10440 skip-level escalated to Tier 4 (Falcon) — Security', ticket: 'TKT-10440', time: '3h ago', read: false },
  { id: 'n3', type: 'assignment', title: 'TKT-10447 assigned to you by Sneha Pillai', ticket: 'TKT-10447', time: '4h ago', read: false },
  { id: 'n4', type: 'reply', title: 'TKT-10435: Meera Iyer replied to your note', ticket: 'TKT-10435', time: '5h ago', read: true },
  { id: 'n5', type: 'resolved', title: 'TKT-10443 marked resolved — awaiting CSAT', ticket: 'TKT-10443', time: 'Yesterday', read: true },
  { id: 'n6', type: 'mention', title: 'Sneha Pillai mentioned you in TKT-10450', ticket: 'TKT-10450', time: 'Yesterday', read: true },
  { id: 'n15', type: 'breach', title: 'TKT-10456 resolution SLA breached — rate card issue', ticket: 'TKT-10456', time: '18 min ago', read: false },
  { id: 'n16', type: 'assignment', title: 'TKT-10419 requires assignment — customs validation', ticket: 'TKT-10419', time: '45 min ago', read: false },
  { id: 'n17', type: 'reply', title: 'TKT-10453: Ingrid Hoffmann added shipment documents', ticket: 'TKT-10453', time: '1h ago', read: true },
]

export const mockChildTasks = [
  { id: 'CT-001', title: 'Reproduce duplicate invoice generation', assignee: 'Arjun Mehta', assigneeInitials: 'AM', status: 'done' as const, dueDate: '2025-07-22' },
  { id: 'CT-002', title: 'Patch billing engine config for multi-leg routes', assignee: 'Devika Rao', assigneeInitials: 'DR', status: 'in_progress' as const, dueDate: '2025-07-23' },
  { id: 'CT-003', title: 'Awaiting deploy to staging', assignee: 'Kiran Bose', assigneeInitials: 'KB', status: 'blocked' as const, dueDate: '2025-07-24' },
]

/** Active tickets in queue (excludes resolved/closed) */
export function countActiveTickets(tickets: Ticket[] = mockTickets): number {
  return tickets.filter((t) => t.status !== 'resolved' && t.status !== 'closed').length
}

export const dashboardData = {
  kpis: {
    created: { value: 284, delta: '+12%', direction: 'up' as const },
    resolved: { value: 261, delta: '+8%', direction: 'up' as const },
    firstResponseSla: { value: '91.2%', delta: '+1.4pp', direction: 'up' as const },
    resolutionSla: { value: '83.7%', delta: '-2.1pp', direction: 'down' as const },
    escalationRate: { value: '14.3%', delta: '-0.8pp', direction: 'down' as const },
    avgCsat: { value: '4.2', delta: '+0.1', direction: 'up' as const },
    openBacklog: { value: 17, delta: '-3', direction: 'down' as const },
  },
  volumeData: [
    { date: 'Jul 15', created: 38, resolved: 34 },
    { date: 'Jul 16', created: 42, resolved: 40 },
    { date: 'Jul 17', created: 35, resolved: 38 },
    { date: 'Jul 18', created: 48, resolved: 41 },
    { date: 'Jul 19', created: 31, resolved: 35 },
    { date: 'Jul 20', created: 29, resolved: 28 },
    { date: 'Jul 21', created: 44, resolved: 38 },
    { date: 'Jul 22', created: 17, resolved: 7 },
  ],
  slaData: [
    { date: 'Jul 15', firstResponse: 94, resolution: 87 },
    { date: 'Jul 16', firstResponse: 92, resolution: 85 },
    { date: 'Jul 17', firstResponse: 95, resolution: 88 },
    { date: 'Jul 18', firstResponse: 88, resolution: 79 },
    { date: 'Jul 19', firstResponse: 93, resolution: 86 },
    { date: 'Jul 20', firstResponse: 91, resolution: 84 },
    { date: 'Jul 21', firstResponse: 89, resolution: 82 },
  ],
  escalationByTier: [
    { tier: 'Tier 1 (Dept)', stopped: 171, percentage: 60 },
    { tier: 'Tier 2 (Branch)', stopped: 71, percentage: 25 },
    { tier: 'Tier 3 (Company)', stopped: 28, percentage: 10 },
    { tier: 'Tier 4 (Falcon)', stopped: 14, percentage: 5 },
  ],
  csatData: [
    { rating: '5 ★', count: 48 },
    { rating: '4 ★', count: 31 },
    { rating: '3 ★', count: 12 },
    { rating: '2 ★', count: 6 },
    { rating: '1 ★', count: 3 },
  ],
  byCategory: [
    { category: 'Technical', count: 98 },
    { category: 'Billing', count: 64 },
    { category: 'Shipment', count: 72 },
    { category: 'How-to', count: 28 },
    { category: 'Security', count: 14 },
    { category: 'Bug', count: 8 },
  ],
}
